name: PHP_Linter

on:
  pull_request:
    branches:
      - main

jobs:
  compare-repos:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Fetch remotes
      run: |
        pwd
        ls
        git status
        git branch
        cat sample.php
        git remote add repo_2 https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
        git fetch repo_2 ${{ github.event.pull_request.head.ref }}
        git branch -r

    # - name: Set up PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '7.4'

    # - name: test
    #   run: |
    #     git checkout origin/main 
    #     cat sample.php
    #     git checkout -b main_2.0 repo_2
    #     cat sample.php
        

    # - name: Run git diff
    #   run: |
    #     git diff --name-only origin/main..repo_2/${{ github.event.pull_request.head.ref }} \
    #     | grep '.php$' \
    #     | xargs -I {} php -l {}
