name: PHP_Linter_pt.2

on:
  pull_request:
    branches:
      - main

jobs:
  compare-repos:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.4
      with:
        dir: '.'
