name: PHP_Linter

on:
  pull_request:
    branches:
      - main

jobs:
  compare-repos:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Fetch remotes & git diff
      run: |
        git remote add repo_2 https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
        git fetch repo_2 ${{ github.event.pull_request.head.ref }}
        git checkout -b main_2.0 repo_2/${{ github.event.pull_request.head.ref }}
        git diff --name-only origin/main > whatever.txt

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.4
      with:
        dir: './whatever.txt'
