name: Compare Two Repositories

on:
  pull_request:
    branches:
      - main

jobs:
  compare-repos:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout trigger repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run git diff
      run: |
        git fetch --all
        git diff --name-only origin/main..HEAD
        | grep '.php$' \
        | xargs -I {} php -l {}
