name: PHP_Linter_pt2

on:
  pull_request:
    branches:
      - main

jobs:
  compare-repos:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

      # Checks out the main branch of the repo where the yml file is stored

    - name: Fetch remotes & git diff
      run: |
        git remote add repo_2 https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git 
        git fetch repo_2 ${{ github.event.pull_request.head.ref }}
        git checkout -b main_2.0 repo_2/${{ github.event.pull_request.head.ref }}
        mkdir test
        git diff --name-only origin/main | grep '\.php$' | xargs -I {} cp {} ./test

      # Adds the repo and branch associated with the pull request that triggered the workflow
      # Checks out the pull request branch to first repo
      # git diff pulls in the php files that have changed from the main branch to the pull request branch

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.4
      with:
        dir: './test'
