name: Compare Two Repositories

on:
  pull_request:
    branches:
      - main

jobs:
  compare-repos:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: whatever
      run: |
        git remote add repo_2 https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
        git fetch repo_2 ${{ github.event.pull_request.head.ref }}
        git diff --name-only repo_2/${{ github.event.pull_request.head.ref }}..${{ github.repository.split('/')[1] }}/main

    # - name: Set up PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '7.4'

    # - name: Run git diff
    #   run: |
    #     git fetch --all
    #     git branch
    #     git diff --name-only origin/main..HEAD \
    #     | grep '.php$' \
    #     | xargs -I {} php -l {}
