name: Compare Two Repositories

on:
  pull_request:
    branches:
      - main

jobs:
  compare-repos:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout trigger repository
      uses: actions/checkout@v4

    - name: Add remote
      run: |
        git remote add origin https://github.com/${{ github.repository }}.git
        git fetch origin ${{ github.head_ref }}
        git checkout -b main-2.0 origin/${{ github.head_ref }}
        git diff --name-only main..main-2.0
      # The above will change to flowershopnetwork/main.git

    # - name: Set up PHP
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '7.4'

    # - name: Run git diff
    #   run: |
    #     git diff --name-only --no-index repo-one repo-two \
    #     | grep '.php$' \
    #     | xargs -I {} php -l {}
