name: PHP_Linter

on:
  pull_request:
    branches:
      - main

jobs:
  linting_php_files:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

      # Checks out the main branch of the repo where the yml file is stored

    - name: Fetch remotes & git diff
      run: |
        var1=$(git remote add repo_2 https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git)
        var2=$(git fetch repo_2 ${{ github.event.pull_request.head.ref }}"
        var3=$(git checkout -b main_2.0 repo_2/${{ github.event.pull_request.head.ref }})
        echo "var1"
        echo "var2"
        echo "var3"
        
      # mkdir lint
        # git diff -z --name-only --diff-filter=AM main...main_2.0 -- '*.php' | xargs -0 cp --parents -t ./lint
        # ls ./lint

      # Adds the repo and branch associated with the pull request that triggered the workflow
      # Checks out the pull request branch to first repo
      # git diff pulls in the added and modified php files (and their paths) that have changed from the pull request branch relative to the main branch 

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.4
      with:
        dir: './lint'
