name: PHP_Linter

on:
  pull_request:
    branches:
      - main

jobs:
  linting_php_files:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Fetch remotes & git diff
      run: |
        git remote add repo_2 https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
        git fetch repo_2 ${{ github.event.pull_request.head.ref }}
        git checkout -b main_2.0 repo_2/${{ github.event.pull_request.head.ref }}
        mkdir lint
        git diff -z --name-only --diff-filter=AM main...main_2.0 -- '*.php' | xargs -0 cp --parents -t ./lint
        ls ./lint

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.4
      with:
        dir: './lint'
